# 场景3: Redis缓存宕机
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: redis-cart-kill
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      "app": "redis-cart"
  gracePeriod: 0  # 立即终止
  duration: "10m"