# 场景4: 杀死随机一个默认命名空间的 Pod
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-demo
  namespace: chaos-testing  # Chaos Mesh 实验所在的命名空间
spec:
  action: pod-kill  # 故障类型：杀死Pod
  mode: one         # 随机选择一个符合条件的Pod
  selector:
    namespaces:
      - default     # 目标Pod所在的命名空间
  gracePeriod: 0    # 立即终止（不等待）
  duration: "10m"   # 实验持续时间（实际pod-kill是瞬时动作，此为实验窗口期）